// =============================================================================
// Persona Decision Tree — GENERATED by trainPersonaModel.js
// DO NOT EDIT MANUALLY — re-run training script to regenerate.
//
// Target label: customerPersona
// Features: groupPresence, interactionDurationSec, membershipTier, timeOfDay
// Algorithm: CART (Gini impurity), max_depth=5, min_samples=2
// Generated: 2026-05-08T06:00:30.769Z
// =============================================================================

const personaDecisionTree = {
  "id": "persona_node_0",
  "label": "groupPresence eq true?",
  "condition": {
    "field": "groupPresence",
    "operator": "eq",
    "value": true
  },
  "yes": {
    "id": "persona_leaf_1",
    "label": "Leaf: FAMILY_CUSTOMER (100%)",
    "result": {
      "customerPersona": "FAMILY_CUSTOMER",
      "confidence": 1,
      "reason": "9 training samples, 100% purity",
      "membershipInfluenced": false
    }
  },
  "no": {
    "id": "persona_node_2",
    "label": "timeOfDay in [\"MORNING\",\"EVENING\"]?",
    "condition": {
      "field": "timeOfDay",
      "operator": "in",
      "value": [
        "MORNING",
        "EVENING"
      ]
    },
    "yes": {
      "id": "persona_node_3",
      "label": "membershipTier in [\"PREMIUM\",\"LOYALTY\"]?",
      "condition": {
        "field": "membershipTier",
        "operator": "in",
        "value": [
          "PREMIUM",
          "LOYALTY"
        ]
      },
      "yes": {
        "id": "persona_leaf_4",
        "label": "Leaf: BUSINESS_TRAVELLER (100%)",
        "result": {
          "customerPersona": "BUSINESS_TRAVELLER",
          "confidence": 1,
          "reason": "9 training samples, 100% purity",
          "membershipInfluenced": true
        }
      },
      "no": {
        "id": "persona_leaf_5",
        "label": "Leaf: LEISURE_TRAVELLER (100%)",
        "result": {
          "customerPersona": "LEISURE_TRAVELLER",
          "confidence": 1,
          "reason": "1 training samples, 100% purity",
          "membershipInfluenced": false
        }
      }
    },
    "no": {
      "id": "persona_leaf_6",
      "label": "Leaf: LEISURE_TRAVELLER (100%)",
      "result": {
        "customerPersona": "LEISURE_TRAVELLER",
        "confidence": 1,
        "reason": "11 training samples, 100% purity",
        "membershipInfluenced": false
      }
    }
  }
};

export default personaDecisionTree;
