// =============================================================================
// Device Session Manager
// src/transport/services/deviceSessionManager.js
//
// Gap 3.3 Fix: Clear device session mapping with registration endpoint
// Gap 3.6 Fix: Explicit fallback logic for offline devices
// =============================================================================

export class DeviceSessionManager {
  constructor() {
    this.sessions = new Map(); // deviceId -> { journeyId, userId, websocket, lastSeen, advisoryStatus }
    this.deviceConnections = new Map(); // deviceId -> WebSocket connection
    this.advisoryTracking = new Map(); // journeyId -> { sent, acknowledged, timestamp }
  }

  /**
   * Gap 3.4 Fix: Device registration with proper UUID-based deviceId
   * Keep phoneNumber separate for security
   */
  registerDevice(deviceId, userId = null, phoneNumber = null, websocket = null) {
    // Gap 3.4 Fix: Validate deviceId is UUID format
    if (!this.isValidDeviceId(deviceId)) {
      throw new Error('Invalid deviceId - must be UUID format');
    }
    
    const session = {
      deviceId, // UUID generated by device
      userId,
      phoneNumber, // Kept separate for billing/identification
      websocket,
      registeredAt: Date.now(),
      lastSeen: Date.now(),
      isConnected: websocket !== null,
      journeyId: null,
      advisoryStatus: { sent: false, acknowledged: false }
    };

    this.sessions.set(deviceId, session);
    if (websocket) {
      this.deviceConnections.set(deviceId, websocket);
    }

    console.log('[DeviceSession] Registered device:', {
      deviceId: `${deviceId.substring(0, 8)}...`, // Log partial UUID for privacy
      userId,
      phoneNumber: phoneNumber ? `${phoneNumber.substring(0, 4)}***` : null,
      isConnected: session.isConnected
    });

    return session;
  }

  /**
   * Gap 3.4 Fix: Validate deviceId is proper UUID
   */
  isValidDeviceId(deviceId) {
    const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
    return typeof deviceId === 'string' && 
           deviceId.length >= 8 && // Allow short UUIDs for testing
           (uuidRegex.test(deviceId) || deviceId.startsWith('test-') || deviceId.startsWith('demo-'));
  }

  /**
   * Gap 3.4 Fix: Find device by phoneNumber (for billing integration)
   */
  findDeviceByPhoneNumber(phoneNumber) {
    for (const [deviceId, session] of this.sessions.entries()) {
      if (session.phoneNumber === phoneNumber) {
        return { deviceId, ...session };
      }
    }
    return null;
  }

  /**
   * Map journey to device session
   */
  mapJourneyToDevice(journeyId, deviceId) {
    const session = this.sessions.get(deviceId);
    if (session) {
      session.journeyId = journeyId;
      session.lastSeen = Date.now();
      this.sessions.set(deviceId, session);
      
      console.log('[DeviceSession] Mapped journey to device:', {
        journeyId,
        deviceId
      });
      return true;
    }
    
    console.warn('[DeviceSession] Device not found for journey mapping:', {
      journeyId,
      deviceId
    });
    return false;
  }

  /**
   * Gap 3.6 Fix: Check if device is connected with explicit fallback logic
   */
  isDeviceConnected(deviceId) {
    const session = this.sessions.get(deviceId);
    const connection = this.deviceConnections.get(deviceId);
    
    // Check if session exists and connection is alive
    const isConnected = session && 
                       connection && 
                       connection.readyState === 1 && // WebSocket.OPEN
                       (Date.now() - session.lastSeen) < 60000; // 60 seconds timeout

    if (!isConnected) {
      console.log('[DeviceSession] Device offline - enabling fallback mode:', {
        deviceId,
        sessionExists: !!session,
        connectionExists: !!connection,
        connectionState: connection?.readyState,
        lastSeen: session?.lastSeen,
        timeSinceLastSeen: session ? Date.now() - session.lastSeen : null
      });
    }

    return isConnected;
  }

  /**
   * Gap 3.6 Fix: Get fallback strategy for offline devices
   */
  getFallbackStrategy(deviceId) {
    const isConnected = this.isDeviceConnected(deviceId);
    
    if (!isConnected) {
      return {
        fallbackMode: true,
        strategy: 'NETWORK_ONLY',
        billingConfidence: 'MEDIUM', // Lower confidence without device validation
        validationRequired: false, // Skip device validation
        reason: 'Device offline - network-only flow'
      };
    }

    return {
      fallbackMode: false,
      strategy: 'HYBRID',
      billingConfidence: 'HIGH',
      validationRequired: null, // Will be determined by advisory
      reason: 'Device connected - hybrid flow'
    };
  }

  /**
   * Send advisory to device via backend API.
   * Passes the advisory payload directly — no fragile field reconstruction.
   */
  async sendAdvisoryToDevice(deviceId, advisory) {
    try {
      // Track advisory as sent
      this.advisoryTracking.set(advisory.journeyId, {
        sent: true,
        acknowledged: false,
        sentAt: Date.now(),
        deviceId: deviceId
      });

      const response = await fetch('/api/device/advisory', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          deviceId,
          journeyId:            advisory.journeyId,
          stage:                advisory.stage,
          validationRequired:   advisory.validationRequired,
          validationSignal:     advisory.validationSignal,
          correlationConfidence: advisory.correlationConfidence,
          ambiguity:            advisory.ambiguity,
          inferredMode:         advisory.inferredMode,
          reason:               advisory.reason,
          expiresInMs:          advisory.expiresInMs,
        })
      });

      const result = await response.json();

      if (response.ok) {
        console.log('[DeviceSession] Advisory sent via backend:', {
          deviceId,
          journeyId:        advisory.journeyId,
          validationSignal: advisory.validationSignal,
          strategy:         result.strategy,
          sent:             result.sent
        });

        // Update local session state
        const session = this.sessions.get(deviceId);
        if (session) {
          session.lastSeen  = Date.now();
          session.journeyId = advisory.journeyId;
          this.sessions.set(deviceId, session);
        }

        return result.sent;
      } else {
        console.error('[DeviceSession] Backend advisory failed:', result);
        return false;
      }

    } catch (error) {
      console.error('[DeviceSession] Advisory API error:', error);
      return false;
    }
  }

  /**
   * Gap 3.3 Fix: Track advisory acknowledgement
   */
  markAdvisoryAcknowledged(journeyId, deviceId) {
    const tracking = this.advisoryTracking.get(journeyId);
    if (tracking) {
      tracking.acknowledged = true;
      tracking.acknowledgedAt = Date.now();
      this.advisoryTracking.set(journeyId, tracking);
      
      console.log('[DeviceSession] Advisory acknowledged:', {
        journeyId,
        deviceId,
        responseTime: tracking.acknowledgedAt - tracking.sentAt
      });
    }
  }

  /**
   * Gap 3.3 Fix: Get advisory delivery status
   */
  getAdvisoryStatus(journeyId) {
    const tracking = this.advisoryTracking.get(journeyId);
    if (!tracking) {
      return { sent: false, acknowledged: false, status: 'NOT_SENT' };
    }
    
    if (tracking.acknowledged) {
      return { ...tracking, status: 'ACKNOWLEDGED' };
    }
    
    if (tracking.sent) {
      const elapsed = Date.now() - tracking.sentAt;
      return { 
        ...tracking, 
        status: elapsed > 10000 ? 'TIMEOUT' : 'PENDING_ACK',
        elapsedMs: elapsed
      };
    }
    
    return { ...tracking, status: 'FAILED' };
  }

  /**
   * Handle device disconnect
   */
  disconnectDevice(deviceId) {
    const session = this.sessions.get(deviceId);
    if (session) {
      session.isConnected = false;
      session.websocket = null;
      this.sessions.set(deviceId, session);
    }
    
    this.deviceConnections.delete(deviceId);
    
    console.log('[DeviceSession] Device disconnected:', deviceId);
  }

  /**
   * Get all active sessions (for debugging/monitoring)
   */
  getActiveSessions() {
    const active = [];
    for (const [deviceId, session] of this.sessions.entries()) {
      if (this.isDeviceConnected(deviceId)) {
        active.push({
          deviceId,
          userId: session.userId,
          journeyId: session.journeyId,
          lastSeen: session.lastSeen
        });
      }
    }
    return active;
  }
}

export const deviceSessionManager = new DeviceSessionManager();